/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const Asset = require ('../Model/Asset');
const BaseApi = require('./BaseApi');

/**
* Asset service.
* @module Api/AssetApi
* @version 1.0.0
*/
module.exports = class AssetApi extends BaseApi{

    constructor(authBasePath, clientId, clientSecret, accountId, scope) {
        super(authBasePath, clientId, clientSecret, accountId, scope);
    }

    /**
     * createAsset
     * Creates a new asset.
     * @param {Object} opts Optional parameters
     * @param {module:Model/Asset} opts.body JSON Parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/Asset} and HTTP response
     */
    createAssetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['body'];


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = Asset;

      return this.apiClient.callApi(
        '/asset/v1/content/assets', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * createAsset
     * Creates a new asset.
     * @param {Object} opts Optional parameters
     * @param {module:Model/Asset} opts.body JSON Parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/Asset}
     */
    createAsset(opts) {
      return this.createAssetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * deleteAssetById
     * Deletes an asset.
     * @param {Number} id The ID of the asset to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteAssetByIdWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteAssetById");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/asset/v1/content/assets/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * deleteAssetById
     * Deletes an asset.
     * @param {Number} id The ID of the asset to delete
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteAssetById(id) {
      return this.deleteAssetByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * getAssetById
     * Gets an asset by ID.
     * @param {Number} id The ID of the asset
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/Asset} and HTTP response
     */
    getAssetByIdWithHttpInfo(id) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAssetById");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = Asset;

      return this.apiClient.callApi(
        '/asset/v1/content/assets/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * getAssetById
     * Gets an asset by ID.
     * @param {Number} id The ID of the asset
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/Asset}
     */
    getAssetById(id) {
      return this.getAssetByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * partiallyUpdateAssetById
     * Updates part of an asset.
     * @param {Number} id The ID of the asset to update
     * @param {Object} opts Optional parameters
     * @param {module:Model/Asset} opts.body JSON Parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Model/Asset} and HTTP response
     */
    partiallyUpdateAssetByIdWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['body'];

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling partiallyUpdateAssetById");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = Asset;

      return this.apiClient.callApi(
        '/asset/v1/content/assets/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * partiallyUpdateAssetById
     * Updates part of an asset.
     * @param {Number} id The ID of the asset to update
     * @param {Object} opts Optional parameters
     * @param {module:Model/Asset} opts.body JSON Parameters
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Model/Asset}
     */
    partiallyUpdateAssetById(id, opts) {
      return this.partiallyUpdateAssetByIdWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
