/**
 * Marketing Cloud REST API
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalesforceMarketingCloud);
  }
}(this, function(expect, SalesforceMarketingCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateEmailDefinitionRequest', function() {
    it('should create an instance of CreateEmailDefinitionRequest', function() {
      // uncomment below and update the code to test CreateEmailDefinitionRequest
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be.a(SalesforceMarketingCloud.CreateEmailDefinitionRequest);
    });

    it('should have the property requestId (base name: "requestId")', function() {
      // uncomment below and update the code to test the property requestId
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property definitionKey (base name: "definitionKey")', function() {
      // uncomment below and update the code to test the property definitionKey
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property definitionId (base name: "definitionId")', function() {
      // uncomment below and update the code to test the property definitionId
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property classification (base name: "classification")', function() {
      // uncomment below and update the code to test the property classification
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property createdDate (base name: "createdDate")', function() {
      // uncomment below and update the code to test the property createdDate
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property modifiedDate (base name: "modifiedDate")', function() {
      // uncomment below and update the code to test the property modifiedDate
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property subscriptions (base name: "subscriptions")', function() {
      // uncomment below and update the code to test the property subscriptions
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instane = new SalesforceMarketingCloud.CreateEmailDefinitionRequest();
      //expect(instance).to.be();
    });

  });

}));
